### ISSUE TITLE
Update landing pages

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendraio-app#101]
We need to update the follow landing pages to say something (if they are blank) or reflect the latest info about what is going on and where (if there is already something written). This is a task for everyone. Something is better than nothing. And quicker is better:

- [x] https://app.kendra.io
  - need landing text to explain what this is (@darrenmothersele or @tim-deighton)
- [x] https://www.kendra.io/kendraio-app
  - need to update text to reflect (@dahacouk)
- https://github.com/kendraio/kendraio-app
  - this text is fine for the moment so we could use this for two above.

**Comment by dahacouk** [comment]
@darrenmothersele to make Flow for https://app.kendra.io root directory.

**Comment by darrenmothersele** [comment]
@dahacouk default route is now using core/dashboard Flow ;)

**Comment by dahacouk** [comment]
This looked done to me. Closing.
