### ISSUE TITLE
Change wording on Connect page...

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendraio-app#162]
On the Connect page ( https://app.kendra.io/connect ) please can we remove "You are viewing a preview of the new connect page" and move "click here for the old account page" to below the main list on that page?

**Comment by darrenmothersele** [comment]
Even better, let's work out and make the required changes to blocks so this page can be built with a Flow

**Comment by dahacouk** [comment]
Yes! That's would be real good!

**Comment by dahacouk** [comment]
While we're at it can we add a "Sign up" button and also a status indicator to show if you are currently logged in or not?

**Comment by darrenmothersele** [comment]
at the moment, the "status indicator" is actually the "last verified" column. I guess we could combine with with the token expiry time to work out if the session is valid

**Comment by darrenmothersele** [comment]
I've updated the page as per the original request. To migrate to using Flows for this screen we will need to drop the link to the old account page. Is that OK?

**Comment by dahacouk** [comment]
> at the moment, the "status indicator" is actually the "last verified" column. I guess we could combine with with the token expiry time to work out if the session is valid

Sounds great!

**Comment by dahacouk** [comment]
> I've updated the page as per the original request. To migrate to using Flows for this screen we will need to drop the link to the old account page. Is that OK?

Awesome. Yes.

**Comment by gsambrotta** [comment]
@dahacouk Are you ok to close this issue and open a new one for the new requested changes?
The title is misleading

**Comment by dahacouk** [comment]
@gsambrotta I'm not sure if you are asking me to do this or offering to do this yourself. In future can you be clearer who you are suggesting does the work of writing the new issue? In any case, your suggestion is good. May I request that you do this? Also, can you make sure that there is some bi-directional reference between this and the new issue? Many thanks.

**Comment by gsambrotta** [comment]
I was asking you to do it @dahacouk, as you are the owner of this issue. 

Sure, I can take care of it. No problem

**Comment by dahacouk** [comment]
Thanks @gsambrotta .

**Comment by gsambrotta** [comment]
Closing this issue and creating a new one #430 for the new requested feature.
