### ISSUE TITLE
Kendraio Player Flow updates

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendraio-app#167]
Regarding the Kendraio Player Flow located at https://app.kendra.io/player/all . Let's...
- [x] Change the title to _Kendraio Player_.
- [x] Add a text introduction at the top that can have a sentence explaining what's going on.
- [x] Text intro can link to posts and video when they exist.
- [x] Make the DSP column be _DSP1_.
- [x] Refer to real artist name and real track name if there is an track. Let's not use _test_ anywhere unless we really, really have to.

For the Web Money Block/Unit/Flow:
- [x] Remove the paused emoji and have the text be _Status: Paused_
- [x] Remove the playing emoji and have the text be _Status: Playing_ 
- [x] Add Payment pointer heading: e.g: _Payment pointer: $ilp.uphold..._
- [x] Remove: _Learn about Web Monetization here. Join Coil here._

**Comment by lukestanley** [comment]
I've done all the quick changes I can for the flow (I've not looked at the DSP column mapping trickery yet) or made any repo changes.
These items remain:

Text intro can link to posts and video when they exist.
Make the DSP column be DSP1.

These ones require a PR with code changes:
 Remove the playing emoji and have the text be _Status: Playing. _
Add Payment pointer heading: e.g: Payment pointer: $ilp.uphold...

**Comment by lukestanley** [comment]
All done and deploying to dev.
