### ISSUE TITLE
Interlink Envoke schema mapping

### ISSUE THREAD

**Issue by lukestanley** [kendraio/kendraio-app#206]
So that users trying the Envoke schema mapping demo know whereto go when using it, it should:

- have hyperlinks or buttons to navigate the users from one flow to another,
- have textual descriptions that explain each section.

**Comment by the-greenman** [comment]
I've added a start page to simplify the experience for a normal user: 
https://app.kendra.io/envoke/start

**Comment by the-greenman** [comment]
The preset import page has been cleaned up: https://app.kendra.io/envoke/importUsingPreset

**Comment by the-greenman** [comment]
I've updated the schema Import page:
https://app.kendra.io/schemas/import

**Comment by the-greenman** [comment]
I've got some sanity checking in place in the Schema import page. I'm using logic in the Template block to make it a bit more responsive. It's a handy workaround.

**Comment by the-greenman** [comment]
I've now actually deleted the Envoke flows in the database!
(Local backup created too)

I think I've removed all links to Envoke

**Comment by the-greenman** [comment]
Changes are now all deployed to prod
