### ISSUE TITLE
Reveal flows by tag 

### ISSUE THREAD

**Issue by the-greenman** [kendraio/kendraio-app#218]
Make it possible to browse flows by tag. 

Flow list already contains tag data. Allow a user to select a specific tag. 

Step 1: Allow a tag to be specified in a query parameter. This will allow us to create links to flows with a tag. 
Step 2: Create a UI to allow users to select a tag

For now, only one tag will be selectable at the same time.

**Comment by lukestanley** [comment]
I thought it would be better to have all flows listed, with it's tags.

**Comment by the-greenman** [comment]
Ahhh.... well, actually, this api endpoint already exists!!

https://app.kendra.io/api/tag/deleted

**Comment by the-greenman** [comment]
And, tag data is included in the primary api, it just doesn't get displayed or used - or generally exist

**Comment by the-greenman** [comment]
I've updated the task description to reflect a new plan.

**Comment by the-greenman** [comment]
Ok. creating links to different tags turns out to be tricky. 

I cannot (currently) use a template, because the links are not angular links. 
I cannot currently use actions, because the actions need to by dynamic
