### ISSUE TITLE
Fix flakey Cypress tests

### ISSUE THREAD

**Issue by lukestanley** [kendraio/kendraio-app#246]
- Cypress was sometimes failing to load the initial web app webpage from Vercel.

- In a mapping block E2E test,
[The mapping block fails to disappear, intermittently](https://github.com/kendraio/kendraio-app/runs/4737899699?check_suite_focus=true#step:3:455) before the timeout.
This fixes it by improving the timeout of the assertion.

> "should make new workflow with mapping block:
       AssertionError: Timed out retrying after 4000ms: Expected not to find content: 'Mapping' within the element: <app-workflow-sidenav.ng-tns-c342-3> but continuously found it."

**Comment by the-greenman** [comment]
Not seeing these anymore
