### ISSUE TITLE
YouTube working again

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendraio-app#302]
YouTube doesn't seem to be working as planned. There seems to be issues with Auth0.

Cheers @dahacouk

**Comment by the-greenman** [comment]
Our authentication process fails after a while. 

google responds to tell us that the token is invalid. 

We also get an internal error in Angular: No provider for InjectionToken ng-select-selection-model!

**Comment by dahacouk** [comment]
This has come in from YouTube:

> Hello,
> 
> Thanks for working with us on your YouTube API Services Compliance Review. We are reviewing your response and have found that your API Client is not in compliance with the[ YouTube API Services Terms and Policies](https://developers.google.com/youtube/terms/api-services-terms-of-service). You can find the list of violations in the attached PDF document.
> 
> Please resolve all listed violations within seven (7) business days, to bring your API Client into compliance. 
> 
> We appreciate your cooperation, and look forward to completing your YouTube API Services compliance review. Feel free to reach out to us with any questions.
> 
> Thanks,
> 
> The YouTube API Services Team

From the PDF

> July 4, 2022
> Project Number:1036027844848
> API Client Name: Kendraio Foundation
> ToS Violation Report V.1
> [YouTube API Services - Developer Policies](https://developers.google.com/youtube/terms/developer-policies#iii.-general-developer-policies)
> 
> Violations that required immediate resolution:
> 
> D (Accessing YouTube API Services) [(](https://developers.google.com/youtube/terms/developer-policies#d.-accessing-youtube-api-services)[link](https://developers.google.com/youtube/terms/developer-policies#d.-accessing-youtube-api-services)) Policy #: III.D.1.c ([link](https://developers.google.com/youtube/terms/developer-policies#d.-accessing-youtube-api-services))
> 
> - [Confirm] Please confirm if you use multiple project IDs for the given API Client. If so, please provide all the related project IDs.
> 
> A (API Client Terms of Use and Privacy Policies) [(](https://developers.google.com/youtube/terms/developer-policies#a.-api-client-terms-of-use-and-privacy-policies)[link](https://developers.google.com/youtube/terms/developer-policies#a.-api-client-terms-of-use-and-privacy-policies))
> 
> Policy #: III.A.1,2.a,b,c,e,h ([link](https://developers.google.com/youtube/terms/developer-policies#a.-api-client-terms-of-use-and-privacy-policies))
> 
> - Violation:
>   - API Client did not provide YouTube's Terms of Services link.
>   - No notification in the Privacy Policy saying that the API Client uses YouTube API Services.
>   - No reference/link to Google privacy policy.
>   - API Client didn't mention how user data is being processed and shared with internal and external parties.
>   - No reference to revoke the API Client's access to users data via the Google security settings page at [https://security.google.com/settings/security/permissions](https://myaccount.google.com/permissions).
> 
> Proposed Solution: Kindly add the links of [YouTube](https://www.youtube.com/t/terms)[Terms Of Services](https://www.youtube.com/t/terms)link in the API Client Terms of Service page, [Google Privacy Policy](https://policies.google.com/privacy)and [Google](https://myaccount.google.com/permissions?pli=1)[Security Settings](https://myaccount.google.com/permissions?pli=1)page for users in your Privacy Policy page and also update your Privacy Policy page with the above mentioned point.
> 
> E (Handling YouTube Data and Content) [(](https://developers.google.com/youtube/terms/developer-policies#e.-handling-youtube-data-and-content)[link](https://developers.google.com/youtube/terms/developer-policies#e.-handling-youtube-data-and-content))
> 
> Policy #: III.E.4.a-g (Refreshing, Storing, and Display)[(](https://developers.google.com/youtube/terms/developer-policies#e.-handling-youtube-data-and-content)[link](https://developers.google.com/youtube/terms/developer-policies#e.-handling-youtube-data-and-content))
> 
> - [Confirm] Please confirm whether you are storing any YouTube data.
> 
> Proposed solution: Regarding data storage, we only allow the API Clients to store the public data temporarily, but not more than 30 days and the stored data must either be refreshed or deleted after 30 days.
> 
> Google Confidential
> 
> [Confirm]: We do not have sufficient information to make a decision on a potential violation. Need further clarification.

[Kendraio Foundation_ToS Violation Report V.1.pdf](https://github.com/kendraio/kendraio-app/files/9061664/Kendraio.Foundation_ToS.Violation.Report.V.1.pdf)

**Comment by lukestanley** [comment]
We added the below text in two places, [the YouTube flow page](https://app.kendra.io/youtube/bl1JysracnItvndPkIIo) and [our Privacy page](https://www.kendra.io/privacy):

To use YouTube's API, you must agree to their terms at [YouTube Terms Of Service](https://www.youtube.com/t/terms), and the [Google Privacy Policy](https://policies.google.com/privacy). If you connect with your YouTube account, you can manage your permission later here: [Google Security Settings](https://myaccount.google.com/permissions?pli=1).

This app permits user created Flows to be shared as Flow code or links.
Flows may only store public YouTube data for less than 30 days at a time. Before this duration is reached, the data must be refreshed or deleted. This does not affect your own personal use of your own private account data. For example, storing a list of your own most popular YouTube videos is allowed.

**Comment by dahacouk** [comment]
This has come in from YouTube:

> We would like to inform you that the quota amount has been restored to 40,000 units per day for the project.

Congratulations @the-greenman @lukestanley ! 🥳

**Comment by gsambrotta** [comment]
@dahacouk @lukestanley Can we close this one?

**Comment by dahacouk** [comment]
@gsambrotta I'm good with closing this, yes!

**Comment by lukestanley** [comment]
OAuth for YouTube does work now.
