### ISSUE TITLE
Change Workflow to Flow everywhere

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendraio-app#367]
Change Workflow to Flow everywhere in the user interface. Let's add to this list of where this needs to be done and where it has been done and track it in this issue. At this stage URLs do not need to be changed as that might take too much code work but perhaps we can document where URLs with _Workflow_ in them exist for the moment...
- [x] Rename [Workflow Cloud](https://app.kendra.io/workflowCloud/listWorkflows) > _Flow Cloud_
- [x] Rename [Workflow Builder](https://app.kendra.io/workflow-builder) > _Flow Builder_
- [x] In the settings/cog/Flow draw rename _Workflow ID_ > _Flow ID_
- [x] In the grid list of Flow Cloud rename column _Workflow ID_ > _Flow ID_
- [x] #368
- [x] Lefthand navigation menu: _Workflow_ > _Flow_

**Comment by CodeKrakken** [comment]
- [ ] New flow in Flow Builder comes with metadata "Title: Workflow".

**Comment by lukestanley** [comment]
It's best we focus on the text the UI presents, not the JSON config before allowing different metadata because that's going to require parser changes that will need some thinking through a migration strategy. 

There are also some URL paths for the app that may need to redirect also and may need to pass along parameters they were called with too, possibly including hash parameters also.

**Comment by dahacouk** [comment]
@lukestanley I agree to only focus on the UI display names for the time being, and avoid modifying any URLs or contents (parameters) thereof. So, if some of the requested changes need URLs altering to work then we should question doing them.

Either way, we should look at all these on a case-by-case basis, and implement them one at a time.

**Comment by dahacouk** [comment]
@gsambrotta @lukestanley I'm wondering if a test was made for this issue that would have caught the revert that we just experienced in the Angular 16 upgrade?
