### ISSUE TITLE
Identify components with broken UI - do they need tests too?

### ISSUE THREAD

**Issue by lukestanley** [kendraio/kendraio-app#441]

**Comment by lukestanley** [comment]
@gsambrotta 
I was looking at the GitHub Projects demo video and they converted a check list into Issues, I wanted to see if this was possible so I made an issue for Angular 16 and then pasted the list from the Angular 16 PR comment into  the top of the issue. 
I saw from:
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists
"Tip: You cannot create task list items within closed issues or issues with linked pull requests."
So I am concerned, if I like the issue to the PR, suddenly, automatically making issues for it might not work! This seems kinda weird to me, but anyway, I only wanted to test it for now but if you want the check list made into actual issues, see #440.

**Comment by gsambrotta** [comment]
- @angular/material/menu - Angular 16 has different spacing + hover on buttons
- [ag-grid-angular](https://www.npmjs.com/package/ag-grid-angular) - quite different look + Launch buttons don't show up
- Form is red when error arise

**Comment by gsambrotta** [comment]
I would close this in favour of https://github.com/kendraio/kendraio-app/issues/441 which is more complete of the issue to work on after Angular 16 upgrade

**Comment by dahacouk** [comment]
@gsambrotta did you mean to say "_I would close this in favour of #441_" above? As it seems you are referring to itself, yes?
