### ISSUE TITLE
Modify menu to remove accordion delay...

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendraio-app#58]
Please remove the delay from the accordion effect in the left hand menu. So that it ends up feeling more like: https://bootsnipp.com/snippets/VgZb

And the speed of the folder open should be the same as the folder close please.

**Comment by darrenmothersele** [comment]
I think I already did that, didn't I?

**Comment by darrenmothersele** [comment]
sorry fixed in dev, but not pushed to master yet
