### ISSUE TITLE
Link to Kendraio App doesn't seem to work

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendraio-app#6]
The link to Kendraio App ( https://app.kendra.io ) doesn't seem to work – showing 404. Is it a sign? ;-) Wondering if we should move the hosting to Google Cloud?

**Comment by darrenmothersele** [comment]
CNAME file got removed from the docs folder after I configured Angular to build into that folder. I've added the CNAME back in, so the custom domain is working now.
