### ISSUE TITLE
Old test API import needs updating to use workflow

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendraio-app#61]
The old test API import needs updating to use workflow. It is currently located at:

https://app.kendra.io/test-api

And should we depreciate the old Bloomen import now that we have the API working?

**Comment by darrenmothersele** [comment]
I think this can be achieved using the tools we have now availble in workflow blocks. 

An import workflow would use a HTTP block (check old code for details of the required HTTP call), then a mapping block to extract the data from the response, a "batch" block to run for each item returned, with the new DB block inside the batch, to save items to the local DB.

Other workflows for viewing/editing the data, as per the musicteam/ddex examples.

**Comment by darrenmothersele** [comment]
Import and database screens updated, so closing this issue for now.
