### ISSUE TITLE
Error: ExpressionChangedAfterItHasBeenCheckedError when executing workflows

### ISSUE THREAD

**Issue by darrenmothersele** [kendraio/kendraio-app#78]
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'model: undefined'. Current value: 'model: null'.

**Comment by darrenmothersele** [comment]
Test API import workflow is one example that causes this bug.

**Comment by tim-deighton** [comment]
does this msg show up in a prod build?

**Comment by darrenmothersele** [comment]
No, it's a warning shown on dev builds. Production builds do not show warnings.
It's a sign that something is wrong with binding variables.
It looks like it's the default model value used in one of the block types. 
I'll fix it.

**Comment by tim-deighton** [comment]
good luck

**Comment by darrenmothersele** [comment]
This continues to be an issue. I now found this when combining a context block with a mapping block. It will be fixed by #42 but will keep this issue here in case a temporary solution can be found in the meantime.
