### ISSUE TITLE
Bloomen adapter

### ISSUE THREAD

**Issue by darrenmothersele** [kendraio/kendraio-app#84]
Current work being done on Bloomen configs:

- ~~[ ] ACL (see also #55)~~
- [ ] Update users 
- [ ] Versioning of resources

**Comment by darrenmothersele** [comment]
@dahacouk I didn't note down the decision regarding workflow/adapter issues. Are they being created here? If no, then @BBGuy can move to the appropriate place?

**Comment by BBGuy** [comment]
@dahacouk @darrenmothersele yes we did say kendraio-adapter repo.

**Comment by darrenmothersele** [comment]
Removed ACL TODO as no longer in scope for the Bloomen adapter
