### ISSUE TITLE
List Workflows on one page

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendraio-app#88]
List Workflows on one page and have buttons for edit and copy.

**Comment by darrenmothersele** [comment]
There will be a screen for each adapter which will list all the configs (workflows, database schemas, and forms) within that adapter and allow to add/edit. Perhaps this is the place for the edit/copy workflow feature?
Maybe the option to clone a config into a new or other adapter?

**Comment by darrenmothersele** [comment]
List of Flows:

 - Workflow Cloud - lists all Flows stored on cloud
 - Adapters - separate lists of all Flows within specific adapter

TODO:

 - clone/copy a Flow config into an existing or new adapter
