### ISSUE TITLE
Date Formats

### ISSUE THREAD

**Issue by tim-deighton** [kendraio/kendraio-app#95]
We need a way to format dates in the Workflows, ag-grids and Components. 
Dates can get incredibly problematic with Time Zones and Locals etc In my experience Moment offers the best solutions.

**Comment by darrenmothersele** [comment]
Luxon could also be a good option https://github.com/moment/luxon/blob/master/docs/why.md

**Comment by darrenmothersele** [comment]
For reference:
https://moment.github.io/luxon/docs/manual/formatting.html#table-of-tokens

**Comment by darrenmothersele** [comment]
`formatDate` has been added to JMESPath as a function, available in all mappings/mapping block. 
It has the following implementation:

```
 ([dateString, formatString]) => DateTime.fromISO(dateString).toFormat(formatString)
```

Where `DateTime` is from [luxon](https://moment.github.io/luxon/)

The list of available tokens for use in the format string is here:

https://moment.github.io/luxon/docs/manual/formatting.html#table-of-tokens
